server:
  port: 8007

spring:
  application:
    name: DEPARTMENT-SERVICES

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost